---
sentimentBotToxicityThreshold: 0.7
sentimentBotReplyComment: |
  Please be sure to review the code of conduct and be respectful of other
  users. cc/ @philoserf
updateDocsComment: |
  Thanks for opening this pull request! The maintainers of this repository
  would appreciate it if you would update some of our documentation based on
  your changes.
updateDocsWhiteList:
  - bug
  - maintenance
newIssueWelcomeComment: |
  Thanks for opening your first issue here! Feel free to update the issue as
  you learn more about the problem you are reporting.
newPRWelcomeComment: |
  Thanks for opening this pull request! Please check out the contributing
  guide.
firstPRMergeComment: |
  Congrats on merging your first pull request!
