---
daysUntilStale: 30
daysUntilClose: 90
exemptLabels:
  - maintenance
  - security
  - holding
  - good first issue
  - help wanted
staleLabel: stale
closeComment: true
markComment: |
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
